### PR TITLE
Ubuntu upgrade to 14.04.3

### PR DESCRIPTION
**Pull request by fadenb**

### CODE REVIEW

**Comment by globin** [comment]
:+1:

**Comment by elseym** [comment]
:+1: but can't test right now.
gonna build it tomorrow for `vmware`, `virtualbox`.

**Comment by fpletz** [comment]
@elseym ping

**Comment by elseym** [comment]
whoops. took longer than expected.
just successfully built it with `vmware`, `virtualbox` and tested it against current wasted master.

**Pull request merged**
